# fly.toml app configuration file generated for frosty-wind-9519 on 2023-07-12T16:53:47+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "frosty-wind-9519"
primary_region = "ams"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
