# fly.toml app configuration file generated for frosty-wind-9519 on 2023-07-12T17:10:34+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "frosty-wind-9519"
primary_region = "ams"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/python"]
