# fly.toml app configuration file generated for silent-pond-5245 on 2023-07-14T15:48:06+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "silent-pond-5245"
primary_region = "ams"
